import type { AppServerNotificationBus } from '../../ports/app-server-notification-bus.js';
import type { ApprovalGate } from '../../ports/approval-gate.js';
import type { AttachmentStore } from '../../ports/attachment-store.js';
import type { Clock } from '../../ports/clock.js';
import type { ConfigStore } from '../../ports/config-store.js';
import type { EventBus } from '../../ports/event-bus.js';
import type { ExtensionRuntime } from '../../ports/extension-runtime.js';
import type { GeneratedImageStore } from '../../ports/generated-image-store.js';
import type { IdGenerator } from '../../ports/id-generator.js';
import type { McpStore } from '../../ports/mcp-store.js';
import type { MemoryStore } from '../../ports/memory-store.js';
import type { ModelClient } from '../../ports/model-client.js';
import type { PersistentToolApprovalStore } from '../../ports/persistent-tool-approval-store.js';
import type { PolicyAmendmentStore } from '../../ports/policy-amendment-store.js';
import type { ProjectInstructionLoader } from '../../ports/project-instruction-loader.js';
import type { ProjectWorkflowResolver } from '../../ports/project-workflow-resolver.js';
import type { RuntimeDebugTraceSink } from '../../ports/runtime-debug-trace.js';
import type { RuntimeEnvironmentResolver } from '../../ports/runtime-environment-resolver.js';
import type { SkillRegistry } from '../../ports/skill-registry.js';
import type { ThreadStore } from '../../ports/thread-store.js';
import type { ToolHost } from '../../ports/tool-host.js';
import type { ToolResultStore } from '../../ports/tool-result-store.js';
import type { UsageStore } from '../../ports/usage-store.js';
import type { RuntimeEventWriter } from '../lifecycle/runtime-event-writer.js';

export type AgentLoopOptions = {
  attachmentStore?: AttachmentStore;
  threadStore: ThreadStore;
  modelClient: ModelClient;
  eventBus: EventBus;
  clock: Clock;
  ids: IdGenerator;
  imageStore?: GeneratedImageStore;
  approvalGate?: ApprovalGate;
  appServerNotificationBus?: AppServerNotificationBus;
  configStore?: ConfigStore;
  debugTrace?: RuntimeDebugTraceSink;
  skillRegistry?: SkillRegistry;
  toolHost?: ToolHost;
  usageStore?: UsageStore;
  memoryStore?: MemoryStore;
  mcpStore?: Pick<McpStore, 'listServerInputs'>;
  policyAmendmentStore?: PolicyAmendmentStore;
  persistentToolApprovalStore?: PersistentToolApprovalStore;
  projectInstructions?: ProjectInstructionLoader;
  projectWorkflow?: ProjectWorkflowResolver;
  environmentResolver?: RuntimeEnvironmentResolver;
  eventWriter?: RuntimeEventWriter;
  extensionManager?: Pick<ExtensionRuntime, 'dispatch'>;
  toolResultStore?: ToolResultStore;
};
