import { randomUUID, X509Certificate } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { getCACertificates } from 'node:tls';

type PrepareSandboxCurlTrustBundleOptions = {
  bundledCaPath: string;
  destination: string;
  systemCertificates?: readonly string[];
};

/**
 * Capture the desktop account's Windows trust view before commands are moved to
 * the isolated account. Certificates are public material; private keys never
 * leave the Windows certificate store.
 */
export async function prepareSandboxCurlTrustBundle(
  options: PrepareSandboxCurlTrustBundleOptions,
): Promise<{ bundlePath: string; systemCertificateCount: number }> {
  const bundledCaPath = path.resolve(options.bundledCaPath);
  const bundlePath = path.resolve(options.destination);
  const bundledCa = (await readFile(bundledCaPath, 'utf8')).trimEnd();
  if (!bundledCa.includes('-----BEGIN CERTIFICATE-----')) {
    throw new Error(`Bundled sandbox curl CA file is invalid: ${bundledCaPath}`);
  }

  const systemCertificates = uniqueSystemCertificates(
    options.systemCertificates ?? getCACertificates('system'),
  );
  const contents = [
    '# Generated by Setsuna Desktop. Do not edit.',
    '# Mozilla roots from the pinned curl bundle follow.',
    bundledCa,
    '# Windows system trust certificates captured at desktop startup follow.',
    ...systemCertificates,
    '',
  ].join('\n');

  await mkdir(path.dirname(bundlePath), { recursive: true });
  await writeFileAtomically(bundlePath, contents);
  return { bundlePath, systemCertificateCount: systemCertificates.length };
}

function uniqueSystemCertificates(certificates: readonly string[]): string[] {
  const byFingerprint = new Map<string, string>();
  for (const value of certificates) {
    const certificate = new X509Certificate(value);
    if (!byFingerprint.has(certificate.fingerprint256)) {
      byFingerprint.set(certificate.fingerprint256, certificate.toString().trim());
    }
  }
  return [...byFingerprint.values()];
}

async function writeFileAtomically(destination: string, contents: string): Promise<void> {
  const temporaryPath = `${destination}.tmp-${process.pid}-${randomUUID()}`;
  try {
    await writeFile(temporaryPath, contents, { encoding: 'utf8', mode: 0o600 });
    await rm(destination, { force: true });
    await rename(temporaryPath, destination);
  } finally {
    await rm(temporaryPath, { force: true });
  }
}
