import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { expect, it } from 'vitest';
import { DEFAULT_COMMIT_MESSAGE_PROMPT } from '@setsuna-desktop/feature-review/contracts';
import { createRuntimeServerTestHarness } from '../../support/runtime-server/harness.js';
import { createOpenAiCaptureServer } from '../../support/runtime-server/shared.js';

it('persists a dedicated model and routes commit generation through non-default conversation models and the global default', async () => {
  const harness = await createRuntimeServerTestHarness();
  const servers = await Promise.all(['global', 'conversation', 'dedicated'].map(async (id) => ({
    id, ...await createOpenAiCaptureServer(`feat: generated by ${id}`),
  })));
  const settingsPath = '/v1/features/desktop-review/commit-message/settings';
  const promptPath = '/v1/features/desktop-review/commit-message/prompt';
  const prompt = 'Follow recent commit conventions. Write a subject and a short body describing the staged changes.';
  const conversation = { providerId: 'conversation', modelId: 'conversation-id' };
  const dedicated = { providerId: 'dedicated', modelId: 'dedicated-id' };
  const source = { branch: 'main', status: 'M  src/app.ts', diff: '+const updated = true;', recentMessages: ['fix(app): recent subject\n\nRecent body'] };
  const generate = (modelSelection?: typeof conversation) => harness.runtimeFetch('/v1/features/desktop-review/commit-message', {
    method: 'POST', body: JSON.stringify({ ...source, modelSelection }),
  });
  try {
    await harness.runtimeFetch('/v1/config', {
      method: 'PUT',
      body: JSON.stringify({
        activeProviderId: 'global',
        providers: servers.map(({ id, baseUrl }) => ({
          id, name: id, provider: 'openai-compatible', baseUrl, apiKey: `sk-${id}`, enabled: true,
          models: [
            { id: `${id}-default-id`, name: `${id} default`, code: `${id}-default-code`, enabled: true, thinkingEnabled: false, thinkingEfforts: [] },
            { id: `${id}-id`, name: id, code: `${id}-code`, enabled: false, thinkingEnabled: false, thinkingEfforts: [] },
          ],
        })),
      }),
    });
    const initial = await harness.runtimeFetch(settingsPath);
    expect(initial.availableModels).toEqual(expect.arrayContaining([
      expect.objectContaining(conversation), expect.objectContaining(dedicated),
    ]));
    const initialPrompt = await harness.runtimeFetch(promptPath);
    expect(initialPrompt.prompt).toBe(DEFAULT_COMMIT_MESSAGE_PROMPT);
    const savedPrompt = await harness.runtimeFetch(promptPath, {
      method: 'PATCH', body: JSON.stringify({ expectedRevision: initialPrompt.revision, prompt }),
    });
    await expect(harness.runtimeFetch(promptPath)).resolves.toEqual(savedPrompt);
    await expect(harness.runtimeFetch(settingsPath)).resolves.toEqual({ ...initial, revision: savedPrompt.revision });
    const reviewBefore = await harness.runtimeFetch('/v1/features/desktop-review/settings');
    expect(initial.selection).toBeNull();
    await expect(generate(conversation)).resolves.toEqual({ message: 'feat: generated by conversation' });

    const saved = await harness.runtimeFetch(settingsPath, {
      method: 'PATCH', body: JSON.stringify({ expectedRevision: savedPrompt.revision, selection: dedicated }),
    });
    expect(saved.selection).toEqual(dedicated);
    await expect(generate(conversation)).resolves.toEqual({ message: 'feat: generated by dedicated' });
    await expect(harness.runtimeFetch('/v1/features/desktop-review/settings')).resolves.toEqual(reviewBefore);
    const document = JSON.parse(await readFile(path.join(
      harness.runtimeDataDir, 'runtime', 'features', 'desktop-review', 'settings', 'git-settings.json',
    ), 'utf8'));
    expect(document.data.commitMessageModel).toEqual(dedicated);
    expect(document.data.commitMessagePrompt).toBe(prompt);
    await expect(harness.runtimeFetch(promptPath, {
      method: 'PATCH', body: JSON.stringify({ expectedRevision: initialPrompt.revision, prompt: 'Stale edit' }),
    })).rejects.toThrow('REVISION_CONFLICT');
    await expect(harness.runtimeFetch(promptPath)).resolves.toEqual({ ...savedPrompt, revision: saved.revision });

    // Concurrent settings pages must not overwrite a newer model selection.
    await expect(harness.runtimeFetch(settingsPath, {
      method: 'PATCH', body: JSON.stringify({ expectedRevision: initial.revision, selection: null }),
    })).rejects.toThrow('REVISION_CONFLICT');
    const stale = await harness.runtimeFetch(settingsPath, {
      method: 'PATCH', body: JSON.stringify({ expectedRevision: saved.revision, selection: { ...dedicated, modelId: 'removed' } }),
    });
    await expect(generate(conversation)).resolves.toEqual({ message: 'feat: generated by conversation' });
    const resetModel = await harness.runtimeFetch(settingsPath, {
      method: 'PATCH', body: JSON.stringify({ expectedRevision: stale.revision, selection: null }),
    });
    await expect(generate(conversation)).resolves.toEqual({ message: 'feat: generated by conversation' });
    await harness.runtimeFetch(promptPath, {
      method: 'PATCH', body: JSON.stringify({ expectedRevision: resetModel.revision, prompt: DEFAULT_COMMIT_MESSAGE_PROMPT }),
    });
    await expect(generate()).resolves.toEqual({ message: 'feat: generated by global' });

    for (const server of servers) {
      const request = await server.nextBody;
      expect(request).toMatchObject({ model: server.id === 'global' ? 'global-default-code' : `${server.id}-code` });
      expect(JSON.stringify(request)).toContain(server.id === 'global' ? DEFAULT_COMMIT_MESSAGE_PROMPT.split('\n')[0] : prompt);
      expect(JSON.stringify(request)).toContain('fix(app): recent subject');
    }
  } finally {
    await harness.close();
    await Promise.all(servers.map((server) => server.close()));
  }
});

it('streams provider text through the authenticated generation route before the model finishes', async () => {
  const harness = await createRuntimeServerTestHarness();
  let finish!: () => void;
  const finished = new Promise<void>((resolve) => { finish = resolve; });
  const message = 'feat: add snake game\n\n- Add gameplay and controls\n- Register the game and credits';
  const provider = await createOpenAiCaptureServer(message, () => finished);
  try {
    await harness.runtimeFetch('/v1/config', {
      method: 'PUT', body: JSON.stringify({
        activeProviderId: 'streaming', providers: [{
          id: 'streaming', name: 'Streaming', provider: 'openai-compatible', baseUrl: provider.baseUrl, apiKey: 'sk-test', enabled: true,
          models: [{ id: 'streaming-model', name: 'Streaming model', code: 'streaming-model', enabled: true, thinkingEnabled: false, thinkingEfforts: [] }],
        }],
      }),
    });
    const response = await fetch(`${harness.baseUrl}/v1/features/desktop-review/commit-message`, {
      method: 'POST', headers: { Authorization: `Bearer ${harness.token}`, 'Content-Type': 'application/json', Accept: 'application/x-ndjson' },
      body: JSON.stringify({ branch: 'main', status: 'A  src/snake.ts', diff: '+export function Snake() {}' }),
    });
    expect(response.headers.get('content-type')).toContain('application/x-ndjson');
    const reader = response.body!.getReader();
    const first = await reader.read();
    expect(JSON.parse(new TextDecoder().decode(first.value))).toEqual({ type: 'progress', value: { message } });
    finish();
    const terminal = await reader.read();
    expect(JSON.parse(new TextDecoder().decode(terminal.value))).toEqual({ type: 'result', value: { message } });
    await reader.cancel();
  } finally {
    finish();
    await harness.close();
    await provider.close();
  }
});
